import { getEnv } from '../utils/get-env';

export const Env = {
  NODE_ENV: getEnv('NODE_ENV', 'production'),
  PORT: getEnv('PORT'),
  JWT_VERIFICATION_SECRET: getEnv('JWT_VERIFICATION_SECRET'),
  JWT_ACCESS_SECRET: getEnv('JWT_ACCESS_SECRET'),
  JWT_REFRESH_SECRET: getEnv('JWT_REFRESH_SECRET'),
  JWT_EXPIRESIN: getEnv('JWT_EXPIRESIN'),
  JWT_REFRESH_EXPIRESIN: getEnv('JWT_REFRESH_EXPIRESIN'),
  FRONTEND_URL: getEnv('FRONTEND_URL'),
  GOOGLE_CLIENT_ID: getEnv('GOOGLE_CLIENT_ID'),
  GOOGLE_CLIENT_SECRET: getEnv('GOOGLE_CLIENT_SECRET'),
  GOOGLE_AUTH_CALLBACK: getEnv('GOOGLE_AUTH_CALLBACK'),
} as const;
